services:
  postgres:
    image: postgres:16
    container_name: testpilot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: testpilot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - testpilot-network

  postgres-test:
    image: postgres:16
    container_name: testpilot-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: testpilot_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - testpilot-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: testpilot-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
      - postgres-test
    networks:
      - testpilot-network

volumes:
  postgres_data:
  postgres_test_data:
  pgadmin_data:

networks:
  testpilot-network:
    driver: bridge
